[package]
name = "rdo"
version = "0.3.1"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
crossterm = "0.28.1"
csv = "1.3.0"
dirs = "5.0.1"
libmpv2 = "=4.0.0"
log = "0.4.22"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive" ]}
tui-textarea = "0.6.1"
